-- CREATE TABLE employees (
--     emp_id INT PRIMARY KEY,
--     name VARCHAR(100)
-- );


-- CREATE TABLE employee_audit (
--     audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     emp_id NUMBER,
--     action_type VARCHAR2(20),
--     action_date DATE DEFAULT SYSDATE
-- );


-- CREATE OR REPLACE TRIGGER trg_employee_insert
-- AFTER INSERT ON employees
-- FOR EACH ROW
-- BEGIN
--     INSERT INTO employee_audit (emp_id, action_type, action_date)
--     VALUES (:NEW.emp_id, 'INSERT', SYSDATE);
-- END;

-- INSERT INTO employees (emp_id, name) VALUES (2, 'John Doe');
-- INSERT INTO employees (emp_id, name) VALUES (3, 'Jane Smith');

-- Select * from  employee_audit;
